### ISSUE TITLE
Target Numbers on roll groups

### ISSUE THREAD

**Issue by SebaSOFT** [GreenImp/rpg-dice-roller#86]
**Describe the bug**
There is a difference in the POV of the meaning of this simple formula `2d6>4`
the `>4` part mean **threshold** so every value above 4 will be counted as a success...
but I see many dice rollers (and roll20 which is the most complete reference IMHO) that this means **target number** which will evaluate the roll and then see if that value is bigger than 4.

**To Reproduce**
1. Go to http://rpg.greenimp.co.uk/dice-roller/
2. Imput `2d6>4` on the format box
3. Check the result
4. You can also try  Imput `(2d6)>4` on the format box

**Observed behavior**
1 success for any dice that is above 4

**Expected behavior**
1 success if all the formula totals more than 4

**Comment by GreenImp** [comment]
Interesting. The original request was for it to function as it does currently, where each roll is individually checked for success/failure, rather than the total.

I've also just checked the Roll20 docs, as that's the one you referenced, to see what they do, and it looks like they actually handle it the same way as I am currently: https://wiki.roll20.net/Dice_Reference#Target_Number_.2F_Successes_.28B.2CF.29_-_CP

> `3d6>3` - Roll 3 d6's and count one success for each roll of 3 or higher

What systems handle success/failures on the total, rather than individual rolls, and do you have any suggestions for how to handle the notation for it?
If we can come up with a good way of handling it, I'm all for getting it implemented.

**Comment by SebaSOFT** [comment]
I see what you mean, I guess surrounding the die formula with braces could do the trick since it's meant for comparing multiple dice rolls as a whole.
for my case would be `{2d6}>4` to evaluate the roll before checking for a DC

**Comment by GreenImp** [comment]
Yeah, that could work.
We're currently only checking for modifiers etc. after the dice roll (ie. `2d6>4`). We're not currently doing any checks for things surrounding the dice roll like that. So it shouldn't conflict, but I think it might also take a bit of jiggering around to get it to read that sort of notation.

I've also just seen that Roll20 does something similar, called Grouped Rolls: https://wiki.roll20.net/Dice_Reference#Grouped_Roll_Modifiers
So it sees like there's at least an expectation for that kind of thing.

You're more than welcome to have a go at it yourself, and submit a pull request. Otherwise I'll take a look at it.

**Comment by SebaSOFT** [comment]
I'd love to, but I think for you is going to be a quick fix (or at least you know how to move through the code). I'm using this awesome library to build around a Discord bot, so I'd rather put an effort to finish it and of course credit and link this, the ultimate Dice Rolling Lib :D

**Comment by GreenImp** [comment]
I've created a new task for doing group rolls in general: #88
Once that's done, I can work on enabling success checks for a group.

**Comment by GreenImp** [comment]
I'm glad you're liking the library :) I'm going to start work on the roll groups in task #88, but not sure how quickly I'll get it sorted for you.

**Comment by GreenImp** [comment]
Hey @SebaSoft I just wanted to let you know that this hasn't been forgotten! Adding dice groups (Curly braces) is quite difficult with the current Regex parsing.
I've been rewriting the whole parsing engine to be more flexible, so that I can add features like this. It's still a little way off, but it's progressing.

**Comment by SebaSOFT** [comment]
I love it man, keep up the good work, I will finish my Discord bot and let you know...

**Comment by GreenImp** [comment]
I've just released v4.0.0 which is a complete rewrite of the library.
It doesn't include the group rolls functionality I'm afraid, but it gives me a better base to build it on - It proved to be incredibly difficult to implement with the old regex parsing method.

So my next task is to build the group rolls, which I'll probably start next week. Once done, the library will be functionality comparable to Roll20.

**Comment by GreenImp** [comment]
@SebaSOFT I'm trying to figure out how best to achieve this functionality, whilst also keeping our similar to Roll20.

How would you currently do something like this in Roll20?

I've been reading the docs in [grouped rolls target success / failure](https://wiki.roll20.net/Dice_Reference#Target_Number_.2F_Successes_.28B.2CF.29_-_CP_2). With a single sub-roll, the functionality doesn't seem to be what you're after; it still checks successes against each individual roll. It seems more similar to ones with multiple sub-rolls, but with a single roll.
Unless I'm just misinterpreting this.

I'm just wanting to get it right and how people expect it to be, so feedback would be appreciated.

**Comment by sigfriedmcwild** [comment]
I'd love to see the grouped roll functionality that Roll20 has (even if doesn't do what SebaSOFT asked for initially)

**Comment by GreenImp** [comment]
Hey @sigfriedmcwild thanks for the interest. I'm hoping to look at the group functionality again this week, but no ETA on when it might be complete I'm afraid.

You can follow ticket #88 for a bit more information, and it will be kept more up-to-date.

I'm actually going to close this one, as they're really for the same thing (Not really sure why I created the other one, but it seems as though it's superseded this one).

**Comment by GreenImp** [comment]
In case you're not watching #88 I've just updated it with a request for feedback on how the functionality should work.
If you're interested, I'd appreciate any input, so that I can try and get it working how most people would expect / like.
