### ISSUE TITLE
NodeBB Forum Insertion? 

### ISSUE THREAD

**Issue by michaelpfaff** [GreenImp/rpg-dice-roller#95]
I'm interested in using this code for making posts on forums, specifically for NodeBB. Does anyone have a plugin that already does this? If not, would anyone be interested in developing one? Perhaps if I also made a donation to that person/team?

**Comment by GreenImp** [comment]
Hi @michaelpfaff . I've seen some interesting libraries popping up using the dice roller, but nothing for NodeBB yet.

I've not come across NodeBB before, so wouldn't know where to begin with a plugin for it.
Unfortunately I wouldn't have the time to spend to learn the NodeBB ecosystem to build a plugin for it. I'm currently in the process of rewriting the entire library with a better parsing engine, so that's my priority at the moment.

I'd be really interested if you do find a NodeBB plugin though, or if someone builds one. It's nice to see where it's being used :)

**Comment by michaelpfaff** [comment]
@GreenImp I have the NodeBB guys working on this and it's up and running (we're testing now). Check it out at: https://github.com/NodeBB/nodebb-plugin-dice

**Comment by GreenImp** [comment]
Hey @michaelpfaff that's really cool! Glad you found a way of getting it integrated :)

Let me know when it's tested and released. I'd love to give it a try.

**Comment by michaelpfaff** [comment]
It's live now at our forum and seems to be working well: https://community.nerdlouisville.org/

Feel free to sign up and give it a whirl.

**Comment by GreenImp** [comment]
Nice. I just had a look and found the dice testing topic. Really nice to see it being used.
Also, your site looks good. Seems like a nice idea :)
